// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiwqffnwaajqhlsypguo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imppd3FmZm53YWFqcWhsc3lwZ3VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDU1NDMsImV4cCI6MjA2ODUyMTU0M30.jVf66ko9nzFdZhCoZDZorX7zb-JITa-9K3bVHm5IkEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});